<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="const\**\*.cs" />
    <Compile Include="gdal\**\*.cs" />
    <Compile Include="ogr\**\*.cs" />
    <Compile Include="osr\**\*.cs" />

    <Compile Remove="**\obj\**" />
    <Compile Remove="**\bin\**" />
  </ItemGroup>
</Project>
